server {
    listen 8080;
    root ./root;
    index index.html;
    client_max_body_size 200M;

    error_page 404 ./root/www/errors/404.html;

    location / {
        methods GET;
        autoindex off;
    }

    location /directory {
        methods GET POST;
        root ./YoupiBanane;
        index youpi.bad_extension;
        cgi_type .bla;
        cgi_path ./cgi_tester;
    }

    location /post_body {
        methods GET POST;
        client_max_body_size 100;
	    upload_path ./root/upload;
    }
}
