server {
  listen 127.0.0.1:8080;
  root /var/www/site;
  client_max_body_size 1M;
  error_page 404 /errors/404.html;

  location / {
    methods GET POST;
    index index.html;
    autoindex off;
  }

  location /cgi-bin {
    methods GET POST;
    # cgi por extensão
  }
}